module.exports = [
    {
        city : "Rishikesh",
        state : "Uttarakhand",
        activity_location :  "Rattapani-Neelkanth Road, Rishikesh",
        description: "Situated at a distance of 100 meters from a river stream, surrounded by lush green mountains and a nearby waterfall at walking distance. This campsite offers multiple adrenaline-rushing activities, indoor/outdoor games, bird-watching activities, and a lot more. Indulge in a truly refreshing stay amidst the serenity of nature, with delicious meals, exhilarating activities, comfortable accommodations, and loads of fun! Book this package and make awesome memories with your family and friends",
        lat_long: [30.105855, 78.382247] ,
        name: "Rishikesh Camping With Rafting",
    },
    {
        city : "Rishikesh",
        state : "Uttarakhand",
        activity :  "Near By Jumpin Height Rishikesh",
        description: "The campsite is situated cozily alongside a Himalayan mountain and located at walking distance from the nearby waterfall, the campsite is nestled cozily on a hilly ridge that overlooks the alluring waters of a river stream. Indulge in a truly refreshing experience as you enjoy time with your companions by playing indoor/ outdoor games like cricket, volleyball, badminton, etc. available at the property. Also, chase the thrill by choosing the package offering a 10km &16 km river rafting experience!",
        lat_long: [30.089362, 78.378844] ,
        name: "Beach Camping in Rishikesh with Rafting",
    },
    {
        city : "Panchgani",
        state : "Maharashtra",
        activity :  "Panchgani",
        description: "Panchgani is a beautiful hill station that is considered to be the perfect spot for nature and adventure lovers. Situated at a significant height, surrounded by stunning hills and valley views, this camping experience is a famous option for people looking forward to unwinding themselves away from monotonous daily life. The campsite is set amidst an expansive land of around 20 acres. Guests can also engage themselves in some fun-filled adventure activities. Book this exquisite camping activity and avail the serene experience!",
        lat_long: [17.923450, 73.798056] ,
        name: "Hilltop Camping in Panchghani",
    },
    {
        city : "Lonavala",
        state : "Maharashtra",
        activity :  "Pawna Lake, Maharashtra",
        description: "The exquisite Pawna Lake campsite is situated on a lush green landscape alongside the banks of Pawna Lake, surrounded by misty valleys of the Western Ghat. The setting at Pawna Lake is enhanced by the presence of various tourist attractions such as Lohagad Fort, Tikona Fort, Tung Fort, and Visapur Fort. The serene view and lush green landscape make this place a beautiful destination near Lonavala & Khandala to enjoy an idyllic weekend.",
        lat_long: [18.644994, 73.471925] ,
        name: "Pawna Lake Camping",
    },
    {
        city : "Lonavala",
        state : "Maharashtra",
        activity :  "Tikona Peth, Maharashtra",
        description: "Situated beside a serene lake in Lonavala, this secret camping in the resort offers to be one of the most famous getaways away from the monotonous daily routines. Surrounded by the lush greenery from all sides, the campsite also offers pristine views of the famous Tikona Fort. Indulge in various games and activities available at the campsite and have fun with your loved ones. Book this peaceful camping activity and create some lasting memories with your friends, family or corporate buddies",
        lat_long: [18.644658, 73.512498] ,
        name: "Camping in Lonavala",
    },
    {
        city : "Kolad",
        state : "Maharashtra",
        activity :  "Kolad, Maharashtra",
        description: "The Kundalika rafting camp is ideal for everyone looking for excitement in the middle of nature's lush retreats! It is the favoured hub for all adventure addicts, being only a couple of hours' drive from Mumbai. Encourage yourself by participating in a variety of activities at the campsite. There are comfortable tents available, with two or three shared bases to select from. Relax and enjoy this ideal escape away from the monotony of daily life.",
        lat_long: [18.415916, 73.195073] ,
        name: "Kundalika Rafting Camp",
    },
    {
        city : "Jaisalmer",
        state : "Rajasthan",
        activity :  "Rajputana Desert Camps, Jaisalmer - Sam - Bhanana Marg Kund, Jaisalmer, Rajasthan 345001",
        description: "Situated on the sand dunes of the Thar Desert, this campsite is a wonder waiting to be explored and waiting to dazzle you with its charm. Get a chance to know about the Rajasthani culture as you spend an amazing night on the sands of Jaisalmer. Also, stay in clean and comfortable camps, cottages, or suites and get a comfortable feel. Book this amazing 2 days and 1-night package which includes a camel safari, cultural performance, and a wonderful campfire.",
        lat_long: [26.829406, 70.528447] ,
        name: "Luxury Desert Camping",
    },
    {
        city : "Bhandardara",
        state : "Maharashtra",
        activity :  "Akole, Bhandardara, Maharashtra",
        description: "Bhandardara is a popular tourist destination due to its natural beauty and neighboring attractions such as notable hills, waterfalls, and sights such as the Wilson Dam and Arthur Lake. Camping in Bhandardara Lake gives an amazing experience for you and your loved ones. The campsite allows you to stay in one of the most beautiful camping & picnic locations in the area for nature enthusiasts. Make the most of this wonderful camping trip at Bhandardara and be mesmerized by the Western Ghats' infinite beauty.",
        lat_long: [19.554111, 73.756554] ,
        name: "Bhandardara Camping",
    },
    {
        city : "Sobhar",
        state : "Meghalaya",
        activity :  "Sohbar, Meghalaya",
        description: "Experience adventure and fun with this camping package that is in Sohbar, it lies 10 km apart from Cherrapunji near international borders. The place is blessed with shimmering blue waters and sparkling sunlight. This campsite offers to rejuvenate with its enchanting river, where one can go for boating and swimming right in the blue water. The campsite is located a short walk away from the Wahrew Arch Bridge. Enjoy the delicious meals and comfortable accommodation and grasp a delightful experience. The campsite is equipped with common washroom facilities during the stay. A bonfire session is organized in the evening with mild music gives you a more cheerful experience. Enjoy the dinner prepared by locals over there. Indulge yourself in multiple adventure activities like Kayaking, Snorkeling, and Bonfire arrangement.",
        lat_long: [25.213144, 91.751120] ,
        name: "Camping In Cherrapunji",
    },
    {
        city : "Jaisalmer",
        state : "Rajasthan",
        activity :  "Sand dunes, Jaisalmer, Sam, Rajasthan",
        description: "Situated on the sand dunes of the Thar Desert, this campsite is a wonder waiting to be explored and waiting to dazzle you with its charm. Get a chance to know about the Rajasthani culture as you spend an amazing night on the sands of Jaisalmer. Also, stay in clean and comfortable camps, cottages, or suites and get a comfortable feel. Book this amazing 2 days and 1-night package which includes a camel safari, cultural performance, and a wonderful campfire.",
        lat_long: [26.864282, 70.562807] ,
        name: "Desert Camping In Sam Sand Dunes Jaisalmer",
    },
    {
        city : "Auli",
        state : "Uttarakhand",
        activity :  "Auli, Uttarakhand",
        description: "A fun-filled camping experience at a campsite that is situated on a lush green hilltop that offers spectacular views of mountains all around. This camping experience in Auli offers a guided trek to the alpine meadows of Gorson Bugyal which are perched at an of 10,084 ft.",
        lat_long: [30.526328, 79.565064] ,
        name: "Camping In Auli",
    },
    {
        city : "Kurnool",
        state : "Hyderabad",
        activity :  "Nallamalai jungle camp, Pacheral",
        description: "Hyderabad is the capital of southern India's Telangana state. Along with being a major center for the technology industry, it's home to a mesmerizing network of biodiversity of flora and fauna. The camping site is located amidst deep valleys, gorges, grasslands, and forests, making it a perfect place to explore the unhindered scenic beauty of its natural landscape while promoting conservation education to the visitors.",
        lat_long: [15.401780, 78.715143] ,
        name: "Luxury Desert Camping",
    },
    {
        city : "Kolad",
        state : "Maharashtra",
        activity :  "Roha - Kolad Rd, Sambhe, Maharashtra ",
        description: "The Kundalika rafting camp is ideal for everyone looking for excitement in the middle of nature's lush retreats! It is the favoured hub for all adventure addicts, being only a couple of hours' drive from Mumbai. Encourage yourself by participating in a variety of activities at the campsite. There are comfortable tents available, with two or three shared bases to select from. Relax and enjoy this ideal escape away from the monotony of daily life.",
        lat_long: [18.414959, 73.194976] ,
        name: "Kundalika Rafting Camp",
    },
    {
        city : "Bari",
        state : "Maharashtra",
        activity :  " Kalsubai Peak",
        description: "One of the most offbeat places in Maharashtra, the Kalsubai is the highest peak surrounded by lush green forests and fields. Adventure or nature enthusiasts looking out for an offbeat getaway can enjoy amazing and thrilling activities like camping with trekking. The trek route towards the Kalsubai summit offers an amazing panoramic view of several mountain ranges like Alang, Madangad, Kulang, Ratangad (south-west), and to the south Pabhargad, Ghanchakkar & Harishchandragad. Book this package and camp at the top of the Everest of Maharashtra & relish this fun experience with your companions.",
        lat_long: [19.613201, 73.730348] ,
        name: "Kalsubai Camping",
    },
    {
        city : "Bagmata",
        state : "Maharashtra",
        activity :  "Alibaug Beach Camping, Near Casuarina Beach Resort, Nagaon-Palav Beach Road, Nagaon, Karpewadi, Alibag, Maharashtra ",
        description: "Escape to the serene Alibaug Beach for an unforgettable camping experience filled with breathtaking sunsets, thrilling indoor & outdoor activities, and cozy bonfire evenings. Soak up the peaceful surroundings, connect with nature, and make lasting memories with friends and family on this amazing campsite. Unwind, relax, and let the sounds of the Arabian Sea soothe your mind and heart.",
        lat_long: [26.829406, 70.528447] ,
        name: "Alibaug Beach Camping | An Overnight Camping Experience",
    },
    {
        city : "Kannamangala",
        state : "Karnataka",
        activity :  "Kanva Reservoir",
        description: "Enjoy this unique camping experience in Bangalore, and pitch your tents near the mesmerizing views of the Kanva lake backwaters. See the tranquil vistas of hills and luscious flora that surround the lake's attractiveness from all sides. Wake up in the morning to catch glimpses of an amazing sunrise view while being surrounded by the expansive stretch of crystal clear water.",
        lat_long: [26.829406, 70.528447] ,
        name: "Lakeside Camping in Kanva",
    },
    {
        city : "Jaisalmer",
        state : "Rajasthan ",
        acitvity_location :  " Sam Village, Jaisalmer",
        description: "One of the most beautiful world heritage sites, Jaisalmer is quite popular for its sacred and religious sites, desert festivals, forts, and rich architecture. Being one of the most ethnic yet luxury stays in the Thar Desert of Jaisalmer, the Oasis Camp, Sam consists of well-furnished Deluxe and Luxury Tents as well as exclusive Cottages.",
        lat_long: [26.830400368436383, 70.5351377846472] ,
        name: "Oasis Camp Sam, Jaisalmer",
    },
    {
        city : " Ambalavayal",
        state : "Kerala",
        acitvity_location :  " Edakkal Edakkal Caves road, Ambalavayal, Kerala",
        description: "Wayanad, blessed with charming waterfalls and historical caves, is an ideal spot for nature lovers to experience beautiful green plantations and diverse wildlife. Book this package and enjoy peaceful camping on the hilltop campsites along with an exciting jeep ride from the starting location to the campsite. Various activities, bonfires & delicious meals are included in the package to make sure you make the most of this experience.",
        lat_long: [11.629113832465817, 76.22578382089418] ,
        name: "Camping with Trekking and Jeep Ride at Wayanad",
    },
    {
        city : "jabalpur",
        state : "Madhya Pradesh",
        acitvity_location :  "near to Jabalpur ",
        description: "The wild camping experience in the Kanha jungle provides the opportunity to gather immense delight by undergoing a set of fun-filled activities in the midst of a dense forest. You can enjoy team building activities such as Archery, Jungle walk, Stargazing. You shall also experience a delightful bonfire session and a jungle safari with your loved ones.",
        lat_long: [23.2663,80.0303] ,
        name: "Camping With Jungle Safari At Kanha",
    },
    {
        city : "Indore",
        state : "Madhya Pradesh",
        acitvity_location :  " Patalpani",
        description: "In the vicinity of Patalpani Waterfall, Forestgum campsite is set on the Dhaulagiri viewpoint. It is an ideal campsite where you can relax near a waterfall or can feel waterdrops of it sitting at the campsite, you will experience the healing touch of nature. This place gradually becoming a preferred weekend getaway from Mhow as well as Indore. ",
        lat_long: [22.7708,75.8665] ,
        name: "Overnight Camping At Patalpani, Indore",
    },
    {
        city : "Munnar",
        state : "Kerala",
        acitvity_location :  "Old Munnar, Village, Near Ksrtc bus station",
        description: "Nestles in the scenic beauty, the site is one of the best places to visit in Munnar. Views of misty mountains and serene beauty all around will eave you relaxed. Lush green covered mountains and beauty of the surroundings are calling you for an amazing experience. Here, you will be able to stay in tents under the clear sky. The tents are comfortable and spacious. There are common washrooms for you that are hygienic and clean.",
        lat_long: [10.0701,77.059] ,
        name: "Camping Experienece In Munnar",
    },
    {
        city : "Kodaikanal",
        state : "Tamil Nadu",
        acitvity_location :  "easily be reached by a means of public or private transport.",
        description: "Owning mountains that touch clouds, picturesque lakes and perfect climate, Kodaikanal stands at an altitude of 7200 feet above sea level. Panoramic views of natural beauty make it an ideal place to visit. Amidst the lush areas find a home at the site that offers you perfect accommodation.",
        lat_long: [10.2283,77.4924] ,
        name: "Cottage Stay With Waterfall Trek In Kodaikanal",
    },
    {
        city : "Vagamon",
        state : "Kerala",
        acitvity_location :  " The Urumbi Hill camping spot, located 24 km away from the Vagamon Bus Stop",
        description: "The campsite, based at a 10 km away from Kuttikanam, lets you view the amazing beauty of Urumbi hills which is blessed with peace and scenic tea plantations that surround the camping location. The Camping package provides you with a welcome drink for a joyful start and delicious meals along with tent accommodation and a set of fun games and music to enhance the pleasure of the camping journey.",
        lat_long: [9.6874,76.90259999999999] ,
        name: "Camping With Trekking And Meals At Urumbi Hill",
    },
    {
        city : "Dalhousie",
        state : "Himachal Pradesh",
        acitvity_location :  "6 km away from the bus stand ",
        description: "This campsite has A-shaped tents and dome tents available that are available on a double sharing basis. The camping near Dalhousie package has all basic amenities from sleeping bags, common washrooms, electricity connection, dining area to friendly camp staff who are always ready to help. the staff would be serving delicious and healthy meals during the stay. Spend the evening while enjoying a bonfire with music and stargazing.",
        lat_long: [32.5373,75.9928] ,
        name: "Camping Near Dalhousie",
    },
    {
        city : "Nainital",
        state : "Uttarakhand",
        acitvity_location :  " located 18 KM from Nainital near Pangot on Kilbury road",
        description: "A premium camp resort in the peaceful valley of Pangot, near Nainital offering a quality time vacations with a family friendly ambiance, non spicy yet delicious veg only meals, many interesting games and outdoor activities, trekking, DJ/karaoke music and bonfire flavored with the best possible personalized hospitality making the stay at Nature Drops genuinely worthwhile",
        lat_long: [29.4223,79.4049] ,
        name: "Nature Camping In Nanital",
    },
    {
        city : " Malana",
        state : "Himachal Pradesh",
        acitvity_location :  " 38 km away from Bhuntar Bus stand",
        description: "The campsite is located in between the lush green mountain and it features accommodation with garden and a cafe. You can relax and enjoy the food at the open-air cafe overlooking the Parvati valley. Well maintained Alpine tents are provided for stay, each having mattresses, pillows and clean linen with common washroom and free toiletries.",
        lat_long: [32.0585,77.2605] ,
        name: "Hillside Camping In Malana",
    },
    {
        city : "karwar",
        state : "Karnataka",
        acitvity_location :  " located at a distance of 11km from the Dandeli bus stand",
        description: "Grab this chance that gives you the perfect opportunity of exploring the diverse wildlife with so much ease and comfort. This Dandeli Rangers Camp is based on the banks of river Kali and as such, you would be surrounded by lush green sceneries and lavish wildlife along with the serenity of Kali river. This Dandeli Rangers Camp allows you to witness different animals such as tigers, bears, panthers, monkeys, and many more.",
        lat_long: [14.888369355181464, 74.26952074602922] ,
        name: "Dandeli Rangers Camp",
    },
    {
        city : "Marango Rangarik",
        state : "Himachal Pradesh",
        acitvity_location :  " Spiti Valley",
        description: "With this Chandrataal Lake trek, you will be visiting the magical Chandrataal Lake or the 'Lake of the Moon' in Himachal Pradesh. Cossetted by the alluring charm of the mighty Himalayas, this pictorial water reservoir is located at a height of 4,300m in the Lahul and Spiti district.",
        lat_long: [32.24791499854168, 78.03864963484722] ,
        name: "Chandrataal Lake Camping",
    },
    {
        city : "Rishikesh",
        state : "Uttarakhand",
        acitvity_location :  " Shivpuri, Rishikesh",
        description: "The campsite is situated on a lush green landscape that is surrounded by verdant green mountains with a nearby riverside stream. This campsite offers luxury tents with multiple adrenaline-rushing activities, indoor/outdoor games, riverside views, bird-watching activities, and a lot more. Come and have a fun-filled day with your mates and make the most out of your vacation in Rishikesh.",
        lat_long: [30.134661177150523, 78.39053025262061] ,
        name: "Jungle Camping In Rishikesh With Rafting",
    },
    {
        city : "Kolughatta",
        state : " Madhya Pradesh",
        acitvity_location :  "Kolughatta, Madhya Pradesh",
        description: "The campsite is located on the Island, it offers a number of adventure sports. At the location, you get the opportunities to see the number of exotic birds on the trees Stay close to nature and enjoy a perfect getaway. Enjoy a perfect escape in nature and witness the mesmerizing views of hills, lakes, dense greenery and lush flora-fauna culture.",
        lat_long: [22.551624924228737, 76.39127663430715] ,
        name: "Lakeside Camping and Adventure Experience Indore",
    },
    {
        city : "Kanakpura",
        state : "Karnataka",
        acitvity_location :  "Kanakpura, Bangalore",
        description: "For a true feeling of escape, the Galibore Nature Camp, which lies deep in the deciduous woodlands on the banks of the River Cauvery is a guaranteed bet. Named after the breezy hillock called Galibore that stands right behind it, the camp is established away from what we call civilization.",
        lat_long: [12.282828779967867, 77.37512209760955] ,
        name: "Galibore Nature Camp",
    },
    {
        city : "baggi",
        state : "Himachal Pradesh",
        acitvity_location :  "baggi,Himachal Pradesh",
        description: "Welcome to one of the most scenic treks that would lead you through the hills of Mandi to arrive at the beautiful oval-shaped lake set at a high altitude of almost 9000 ft above sea level - the Parashar Lake.",
        lat_long: [31.5777,76.9701] ,
        name: "Prashar Lake Camping",
    },
    {
        city : "Ramanagara",
        state : "karnataka",
        acitvity_location :  "Hosakere Lakeside, Ramanagara",
        description: "Enjoy a fantastic getaway into nature by joining the enjoyable camping session in Ramanagara, far from the rush of daily life. Get a profound sense of bliss by participating in exhilarating activities at the Q Mango Forest Adventure Camp. While camping out in the woods of Ramnagara, you can also experience the captivating beauty of the region's diverse flora and fauna.",
        lat_long: [12.64447071715574, 77.32878113929148] ,
        name: "Q Mango Forest Adventure Camp",
    },
    {
        city : "Pench",
        state : "Madhya Pradesh.",
        acitvity_location :  "Pench National Park",
        description: "Pench was the place that inspired the fan favorite 'Jungle Book'. The wild and the life here is something that you will not be able to find anywhere else in the world. And this resort stay experience in the jungles of Pench National Park will prove to be the most memorable time you will have in Madhya Pradesh.",
        lat_long: [21.763,79.3391] ,
        name: "Forest Resort Stay Experience In Pench, Madhya Pradesh",
    },
    {
        city : "Wayanad",
        state : "Kerala",
        acitvity_location :  "Wayanad, Kerala",
        description: "Wayanad is a famous hill station located on the fringes of the western ghats of India and right on the border of Kerala and neighboring states. Bordered by the Bandipur Tiger Reserve and housing the Wayanad Wildlife Reserve is also the home to this amazing campsite.",
        lat_long: [11.6854,76.13199999999999] ,
        name: "Rubber Plantation Camping Expereince In Wayanad",
    },
    {
        city : "Bhopal",
        state : "Madhya Pradesh",
        acitvity_location :  "Lawa Khadi, Madhya Pradesh",
        description: "Kolar River is a tributary of the Narmada and flows for about 101 km before meeting the latter. On this river is built the Kolar Dam that plays a pivotal part in providing water to Bhopal. The campsite is located right next to the Reservoir created by the dam.",
        lat_long: [22.969391336764733, 77.33513682345148] ,
        name: "Kolar de Camp",
    },
    {
        city : "Omkareshwar",
        state : "Madhya Pradesh",
        acitvity_location :  "Main mandir marg, Omkareshwar, Madhya Pradesh",
        description: "A grand pilgrim celebration in state of Madhya Pradesh is in the line to present our prayers and offerings to Lord Shiva. The Mahotsav is taking place on a grand scale for the first time and is a way of showing our love and devotion to one of the 12 Jyotirlinga of Shiva.",
        lat_long: [22.2418,76.1494] ,
        name: "Omkareshwar Mahotsav Camping",
    },
    {
        city : "Chennai",
        state : "Tamil Nadu",
        acitvity_location :  "Chinnaiyan Colony, Poongavanapuram, Chennai, Tamil Nadu",
        description: "Gokarna Camping Tour From Chennai,Breakfast & Lunch on days 2 and 3, Dinner on day 2.Overnight stay in tents on a double sharing basis",
        lat_long: [13.0827,80.27069999999999] ,
        name: "Gokarna Camping Tour From Chennai",
    },
    {
        city : "Sakleshpur",
        state : "Karnataka",
        acitvity_location :  "Devaladakere, Sakleshpur",
        description: "A simple camping place amidst the beauty of nature, the property nestles amidst the lush green areas. Surrounded by the mountains, the site allows you to getaway from the hustle and bustle of the city life. With prominent trees in the vicinity, the site becomes an ideal spot. This pocket-friendly stay is exclusively for one group. Stay in cosy and comfortable tents with your friends and family members. There are 3 cleanly maintained washrooms, exclusively built for camping.",
        lat_long: [13.0161,75.67649999999999] ,
        name: "Camping With Outdoor Activities In Sakleshpur ",
    },
    {
        city : "Pune",
        state : " Maharashtra",
        acitvity_location :  "Pune, Maharashtra",
        description: "Are you looking forward to escaping into some mild nature vibes, away from the hustle and bustle of the city? Then this is the perfect option for you. Avail staying at the Avanti Kalagram that comes with complete bliss and lets you enjoy the glimpses of flora and fauna culture of Pune.",
        lat_long: [18.6122,73.5846] ,
        name: "Avanti Kalagram Stay, Pune",
    },
    {
        city : "Nainital",
        state : "Uttarakhand",
        acitvity_location :  "Village-Jakh, Nainital, Uttarakhand",
        description: "This riverside camp is nicely placed in the lap of nature, near the village Jakh. Riverside Camp in Nainital has 2 Swiss tents with attached washroom, 10 Alpine tents and 6 Dome tents with common washrooms. Breakfast, Lunch and Dinner are provided at the campsite, mostly of north Indian Cuisine.",
        lat_long: [29.43129944469401, 79.46458286449331] ,
        name: "Riverside Camp In Nainital",
    },
    {
        city : "Manali",
        state : "Himachal Pradesh",
        acitvity_location :  "Tehsil, Village Nasogi, Manali, Himachal Pradesh",
        description: "Tailored for a short weekend, here is an opportunity to camp amid the scenic Himalayan mountains.Enjoy a short trek around the camp area with friends and family, and delve into the culinary delights from the many cafes around Sarchu. You can also pick from a fair share of adventure activities like rappelling, rock climbing, etc.",
        lat_long: [32.2396,77.1887] ,
        name: "Sarchu Camp",
    },
    {
        city : "Nanital",
        state : "Uttarakhand",
        acitvity_location :  "Gethiya, Paraw",
        description: "Nanital  is Commonly known as the “Lake District of India”, Nainital is one of the most beautiful hill stations in North India.Surrounded by mountains on three sides Nainital is located around the beautiful lake Naini Tal.The stunning frozen Naini Lake, the misty Eco Cave Gardens, the Mall Road for sweeping views of the hazy or snow-covered hills, the Naina Devi Temple, the Snow View Point for spectacular views of the snowy and sleepy town, the surreal Naini Peak, and Jeolikot are some of the best places to visit in Nainitalal",
        lat_long: [29.3683,79.4871] ,
        name: "Adventure Camping In Nanital",
    },
    {
        city : " Sattal",
        state : "Uttarakhand",
        acitvity_location :  "Village Chattola, Sattal, Uttarakhand",
        description: "The mesmerizing location of the Sattal camp will want you to stay longer as it is placed on a hilltop of around 4300 feet that overlooks 7 lakes of Uttrakhand, Sattal. A waterfall nearby with lakes at plunge pool attracts travellers to take adventurous activities like kayaking, swimming, etc. Moreover, the campsite allows you to experience greenery and valley views from all the sides",
        lat_long: [29.3443,79.5294] ,
        name: "Sattal Camp, Uttarakhand",
    },
    {
        city : "Bhopal",
        state : "Madhya Pradesh",
        acitvity_location :  "Salkanpur, Madhya Pradesh",
        description: "Salkanpur camping near Bhopal is a mind blowing experience that you must take as it will leave you with a mesmerizing memories while you explore the dense forests of Ratapani Wildlife Sanctuary.On this tour, you will be seeing some of the most amazing attractions of the region like the Tapkeshwar Mahadev Temple, rock shelters, and the viewpoint from where we can see the whole forest range.",
        lat_long: [22.7465,77.47879999999999] ,
        name: "Jungle Camping At Salkanpur: Bhopal",
    },
    {
        city : "Munnar",
        state : "Kerala",
        acitvity_location :  "Bodimethu - Suryanallei Rd, near, to Suryanallei, Suryanelli, Kerala",
        description: "Enjoy great delight and fun when you opt for this wondrous camping activity in Munnar along with your friends and loved ones. You would cherish each and every moment of this delightful tour that would bring to you the perfect landscape views of the Anaerangal Lake and the Papathy shola, known as butterfly forests.",
        lat_long: [10.047025326109145, 77.21048708158438] ,
        name: "Anaerangal Camp Munnar Day Out",
    },
    {
        city : "Kasol",
        state : "Himachal Pradesh",
        acitvity_location :  "Dera Gopipur, Himachal Pradesh",
        description: "Kasol refers to a small village in Himachal which is based on the banks of the river Parvati. The spot is a prominent tourist attraction that is loved by adventure seekers as the location renders a wide scope for trekking and camping. ",
        lat_long: [32.0823,76.0176] ,
        name: "Camping In The Lap Of Green Valley Beas, Kasol",
    },
    {
        city : "Wayanad",
        state : "Kerala",
        acitvity_location :  "Thirunelli Post, Wayanad",
        description: "The camp is surrounded by Western Ghats on all four sides alongside river Kalindi, providing feels of home with charm of nature. Set on the outskirts of Wayanad, it serves as an exclusive getaway from city lights. Adding up the beauty, this place also allows its guests to experience its pleasant and favorable hill station climate, chills of tropical rainforests.  ",
        lat_long: [11.909,75.9957] ,
        name: "Brahmagiri Camping",
    },
    {
        city : "Kasol",
        state : " Himachal Pradesh",
        acitvity_location :  "1.5 km away from the Kasol market",
        description: "This camping experience at Kasol is a perfect option for a casual vacation. It offers amazing views of the surrounding nature, great food and a comfortable and relaxing stay.",
        lat_long: [32.0169,77.3282] ,
        name: "Jungle Camping In Kasol",
    },
    {
        city : "Manali",
        state : "Himachal Pradesh",
        acitvity_location :  "Tehsil, Village Nasogi, Manali, Himachal Pradesh",
        description: "Camping is a great way to have fun, and if you add activities in there, the enjoyment gets multiplied. Just like at this adventure camp in Manali, where over the course of your stay for 4 days, you will be enjoying activities like river crossing, outdoor games (volleyball, cricket etc.), rock climbing, rappelling, trekking, Burma bridge and commando net. ",
        lat_long: [32.2396,77.1887] ,
        name: "Adventure Camping Experience In Manali",
    },
    {
        city : "Mcleodganj",
        state : "Himachal Pradesh",
        acitvity_location :  "Pause Dwelling Palace, Temple Road, below Buddhist temple, Dharamshala",
        description: "Just 3 km away from Dharamshala, Mcleodganj is one of the most favorite tourist destinations. The place offers the most beautiful, scenic and exciting treks and campsites. Be ready to experience staying in Jungle camps with meals.  ",
        lat_long: [32.2427,76.32169999999999] ,
        name: "Jungle Camping In Mcleodganj",
    },
    {
        city : "Bhimtal",
        state : "Uttarakhand ",
        acitvity_location :  "Main road to Sattal, Aranayam Resort, near Sunny lake, Bhimtal, Uttarakhand",
        description: "Camp Suriya Goan, Sattal is located on the hilltop with birds’ eye view of the valley below. The Camp will offer a comfortable stay. A professional cook will serve delicious food and electricity is available at the campsite. It has 24*7 security with CCTV's.  The camp offers many activities like river crossing, kayaking, Trekking through the jungle and to the nearest waterfall, Nature walk, etc.",
        lat_long: [29.2102,79.32] ,
        name: "Camp Suriya Goan, Saattal",
    },
    {
        city : "Mashobra",
        state : "Himachal Pradesh",
        acitvity_location :  "Mashobra, Shimla",
        description: "Mashobra is a perfect place away from the crowded city, in the cedar forest, and surrounded by the enchanting wilderness where one will find the much-needed peace.The campsite offers comfortable stays in Mud Hut Swiss Tents that come with attached washrooms and a king-size double bed. The camp has all basic and major facilities with a different wooden interior to make you feel that the people here have gone out and brought everything that is necessary for a perfect stay and to make the stay memorable and aesthetically different in the lap of nature.",
        lat_long: [31.1297,77.2287] ,
        name: "Camping In Mashobra, Shimla",
    },
    {
        city : "Dandeli",
        state : "Karnataka",
        acitvity_location :  "Dandeli ",
        description: "Located in the Badgund area, Dandeli Nature Camp is a popular choice for travelers. With its convenient location, the property offers easy access to the city's must-see destinations & adrenaline-pumping activities. Have fun while playing various indoor-outdoor games and partake in water-based activities. You can relax in Jacuzzi, go for a walk, and enjoy the relaxing bonfire session.",
        lat_long: [15.236532868721385, 74.61715315397079] ,
        name: "Dandeli Nature Camp",
    },
    {
        city : "Panchgani",
        state : "Maharashtra",
        acitvity_location :  "Panchgani",
        description: "Panchgani is a beautiful hill station that is considered to be the perfect spot for nature and adventure lovers. Situated at a significant height, surrounded by stunning hills and valley views, this camping experience is a famous option for people looking forward to unwinding themselves away from monotonous daily life. The campsite is set amidst an expansive land of around 20 acres.",
        lat_long: [17.928082196992136, 73.8073325185846] ,
        name: "Hilltop Camping in Panchghani",
    },
    {
        city : "Masinagudi",
        state : "Tamil Nadu",
        acitvity_location :  "Monterosa Colony, Mettupalayam, Ooty, Tamil Nadu",
        description: "Masinagudi, bestowed with abundant natural beauty and forest resources offer a perfect treat to the nature lovers with a great scope of camping and forest activities. Masinagudi implies to a highly cherished adventure spot that is gifted with unbounded beauty of biodiversity and forest species.",
        lat_long: [11.4151,76.68769999999999] ,
        name: "Camp Stay Amidst Wildlife In Masingudi",
    },
    {
        city : "Panchgani",
        state : "Maharashtra",
        acitvity_location :  "Kaswand, Maharashtra",
        description: "Panchgani, which is located amidst the Sahyadri Ranges is a perfect getaway from the warm and humid summers of Maharashtra. Head out for a fun experience in Panchgani that you will fall in love with. Waterbody in the vicinity and vies of misty hills make it a perfect spot to spend time away from the monotonous city life. Relish your stay in cozy and comfortable accommodations and gaze at the starry sky at the night.",
        lat_long: [17.896788564729395, 73.78713783068615] ,
        name: "Natventure Camp Panchgani",
    },
    {
        city : "Malshej",
        state : "Maharashtra",
        acitvity_location :  "Malshej, Maharashtra",
        description: "Among the many beautiful getaways near Mumbai and Pune, Malshej camping is one of them. The environment here is perfect for those who just need to get away & unwind away from the city life. The campsite is surrounded by lush green Sahyadri mountains with a beautiful lake beside it. Enjoy a comfortable stay and spend your night stargazing while you are relaxing with your loved ones. Book this fun-filled camping and enjoy multiple activities that help you reconnect with nature. You will experience nature at its best here. Also, if you are an adventure junkie, then you can go trekking to the beautiful vantage point on your own.",
        lat_long: [19.34127259430968, 73.77575362960602] ,
        name: "Camping in Malshej",
    },
    {
        city : " Pali Marwar",
        state : "Rajasthan",
        acitvity_location :  "JAWAI DAM DISTRICT, Pali Marwar",
        description: "Lying at the heart of an untrammelled wilderness, where leopards roam wild and free, Sujan’s Jawai has luxurious tents, each with oodles of space and privacy that rest encapsulated in a landscape surrounded by craggy granite formations of caves, kopjes, Anogeissus scrub and winding sand river–beds.",
        lat_long: [25.096089064603753, 73.19563113993803] ,
        name: "Sujan Luxury Camp ",
    },
    
];